"""Two-plate analytic benchmark.

Compares the FEM-computed magnetic interaction energy U_mag(z) for a dipole
between two large parallel SC plates against the closed-form image-dipole
series. The image construction for an SC (Meissner) plane is:

    A reflection through a horizontal plate at z = z_p sends
        position (x, y, z)      ->  (x, y, 2 z_p - z)
        moment   (m_x, m_y, m_z) -> (m_x, m_y, -m_z)

    so that B . n vanishes on the plate.

For two plates an infinite series of images is generated by alternating
reflections; we truncate at `n_images` images per direction (typically a few
dozen are enough for sub-percent accuracy).
"""

from __future__ import annotations

from pathlib import Path
import tempfile

import numpy as np

from .config import MAGNET_MOMENT
from .dipole import B_dipole
from .mesh import load_msh
from .potential import U_mag


def _image_dipoles(r0: np.ndarray, m: np.ndarray, d: float, n_images: int):
    """Return the list of image (position, moment) pairs for two SC plates at z=+/-d/2."""
    out = []
    for direction in ("up", "down"):
        pos = np.array(r0, dtype=float)
        mom = np.array(m,  dtype=float)
        for k in range(n_images):
            top_first = (direction == "up")
            use_top = (k % 2 == 0) == top_first
            z_p = +d / 2 if use_top else -d / 2
            pos = pos.copy()
            mom = mom.copy()
            pos[2] = 2.0 * z_p - pos[2]
            mom[2] = -mom[2]
            out.append((pos.copy(), mom.copy()))
    return out


def U_analytic_two_plates(
    z0: float,
    m: np.ndarray,
    plate_separation: float,
    n_images: int = 40,
) -> float:
    """Image-dipole energy for a dipole on the z-axis between two SC plates."""
    r0 = np.array([0.0, 0.0, z0])
    m  = np.asarray(m, dtype=float).reshape(3)
    images = _image_dipoles(r0, m, plate_separation, n_images)

    B_total = np.zeros(3)
    for r_im, m_im in images:
        B_total += B_dipole(r0[None, :], m_im, r_im)[0]
    return -float(np.dot(m, B_total))


# ---------------------------------------------------------------------------

def two_plate_benchmark(
    plate_separation: float = 4e-3,
    plate_half_side: float = 15e-3,
    far_radius: float = 60e-3,
    mesh_size_sc: float = 0.6e-3,
    mesh_size_ff: float = 8e-3,
    mesh_size_near: float | None = None,
    refine_distance: float | None = None,
    subtract_singularity: bool = False,
    n_z: int = 11,
    n_images: int = 40,
    tol_pct: float = 10.0,
    verbose: bool = False,
) -> int:
    """Generate a two-plate mesh, sweep U_mag(z), compare to analytic series.

    Returns 0 on pass (max relative error < tol_pct), 1 on fail.
    """
    from . import generators as G

    # Place the dipole along the z-axis, oriented along +x (parallel to plates).
    m_mag = MAGNET_MOMENT
    m = np.array([m_mag, 0.0, 0.0])

    # Sample z on a symmetric range, avoiding the plates themselves.
    half = 0.45 * plate_separation     # 90 % of the gap
    zs = np.linspace(-half, +half, n_z)

    # --- Analytic ---------------------------------------------------------
    print("Analytic (image series):")
    U_ana = np.array([
        U_analytic_two_plates(z, m, plate_separation, n_images=n_images)
        for z in zs
    ])
    for z, u in zip(zs, U_ana):
        print(f"  z={z*1e3:+.3f} mm  U_ana={u: .6e} J")

    # --- Numeric ----------------------------------------------------------
    print("\nGenerating mesh ...")
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "plates.msh"
        G.two_parallel_plates(
            plate_half_side=plate_half_side,
            plate_thickness=0.5e-3,
            plate_separation=plate_separation,
            far_radius=far_radius,
            mesh_size_sc=mesh_size_sc,
            mesh_size_ff=mesh_size_ff,
            mesh_size_near=mesh_size_near,
            refine_distance=refine_distance,
            output_file=str(path),
            verbose=verbose,
        )
        sct = load_msh(path)
        print(f"  {sct}")

        print("\nFEM solve at each z ...")
        U_num = np.empty_like(U_ana)
        for i, z in enumerate(zs):
            r0 = np.array([0.0, 0.0, z])
            U_num[i] = U_mag(sct, m, r0, subtract_singularity=subtract_singularity)
            print(f"  z={z*1e3:+.3f} mm  U_fem={U_num[i]: .6e} J  "
                  f"U_ana={U_ana[i]: .6e} J  "
                  f"err={(U_num[i]-U_ana[i])/abs(U_ana[i])*100: .3f} %")

    # --- Compare ----------------------------------------------------------
    rel = np.abs(U_num - U_ana) / np.maximum(np.abs(U_ana), 1e-30)
    max_rel = float(rel.max() * 100)
    print(f"\nMax relative error: {max_rel:.2f} %  (tolerance: {tol_pct:.2f} %)")

    if max_rel <= tol_pct:
        print("PASS")
        return 0
    print("FAIL")
    return 1
